# image
image: Visual Studio 2015

# build platform
platform: x64

# clone directory
clone_folder: c:\xmr-stak

install:
  - mkdir c:\xmr-stak-dep
  - curl -sL https://github.com/fireice-uk/xmr-stak-dep/releases/download/v1/xmr-stak-dep.zip -o xmr-stak-dep.zip
  - 7z x xmr-stak-dep.zip -o"c:\xmr-stak-dep" -y > nul
  - call "c:\xmr-stak\CI\appveyor\install_cuda.bat"

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsMSBuildCmd.bat"
  - cd c:\xmr-stak
  - mkdir build
  - cd build
  - set CMAKE_PREFIX_PATH=C:\xmr-stak-dep\hwloc;C:\xmr-stak-dep\libmicrohttpd;C:\xmr-stak-dep\openssl;
  - cmake -G "Visual Studio 15 2017 Win64" -T v140,host=x64 .. -DWIN_UAC=OFF
  - cmake --build . --config Release --target install

test_script:
  - cd c:\xmr-stak\build\bin\Release
  - dir
  - xmr-stak.exe --help
